name: raytracer
version: 0.2.0
author: Demis Bellot <demis.bellot@gmail.com>
description: TypeScript's Ray Tracer ported to Dart
homepage: https://github.com/dartist/raytracer
dependencies:
  browser: '>=0.10.0 <0.11.0'
  vector_math: '>=1.4.3 <1.5.0'
